### ISSUE TITLE
ドメインを設定しよう

### ISSUE THREAD

**Issue by sor4chi** [saitamau-maximum/maxitter#31]
http://133.130.107.69/ が現在のサイトのURLです。maxitter.maximum.vcでアクセスできるように設定しましょう

**Comment by batora9** [comment]
自分やりたいです

**Comment by batora9** [comment]
どこから手を付ければいいでしょうか？
大まかな手順を教えていただけますでしょうか？

**Comment by a01sa01to** [comment]
1. DNS を設定する必要があるので、どう設定すればいいのか調べる
2. 調べたら私にメンション飛ばして何をどうすればいいのか言ってもらう (権限は基本的に Read-only しようという話になったので、私が設定します)
3. ~~DNS の設定をしたらサーバー側の設定もする必要があるのでする~~
4. ~~サーバー側の設定をローカルで確認するには、 `/etc/hosts` (Windows は `C:\Windows\System32\drivers\etc\hosts`) ファイルを編集して `maxitter.maximum.vc` を `127.0.0.1` に対応付ければよいです~~
5. ~~設定を PR 出す~~

ざっくりこんな感じです、わからないことがあれば都度聞いてください～

upd: 3-5 は必要ないらしい

**Comment by batora9** [comment]
CloudflareでDNSレコードタイプA、Nameをmaxitter、Contentを133.130.107.69に設定しました。
