### ISSUE TITLE
Discordへの投稿通知が飛ばない

### ISSUE THREAD

**Issue by batora9** [saitamau-maximum/maxitter#86]
投稿時間のバグ修正（バックエンド）を行った後にDiscordへの投稿通知がされなくなってしまいました。

**Comment by sor4chi** [comment]
まじ？ @batora9 
これは僕のせいかもしれない、確認します

**Comment by sor4chi** [comment]
https://github.com/saitamau-maximum/maxitter/pull/74/files#diff-dec704b60ebde2632503812758e7db9b3b1f663f8b1ac015e670644b5396a2f0R136

この変更じゃないかな、これ以外にマージ前後で変わった部分がないので
